### Warmup with Lists.

In [7]:
l = [1,7,2,4,100]
print(l)
l.append(1024)
print(l)
l.remove(100)
print(l)
l.append(2)
print(l)
l.remove(2)
print(l)

[1, 7, 2, 4, 100]
[1, 7, 2, 4, 100, 1024]
[1, 7, 2, 4, 1024]
[1, 7, 2, 4, 1024, 2]
[1, 7, 4, 1024, 2]


In [13]:
l = []
l.append(1)
l.append(2)
l.append(3)
print(l)
x = []
m = [10,20,30]
x.append(l)
x.append(m)
print(x)
x.append([100,1024,69])
print(x)

[1, 2, 3]
[[1, 2, 3], [10, 20, 30]]
[[1, 2, 3], [10, 20, 30], [100, 1024, 69]]


In [19]:
# Creating a Matrix.
M = []
M.append([1,2,3])
M.append([4,5,6])
M.append([7,8,9])
print(M)
print(M[0])
print(M[1][0])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
4


### Birthday Paradox.

In [1]:
import random
l = []
for i in range(10):
    l.append(random.random())
print(l)

[0.4280026925790652, 0.18040983959079093, 0.6055626029670075, 0.9493278718349192, 0.8963549436134813, 0.8861322330429648, 0.6377350550185662, 0.6649710708066221, 0.7087134509987003, 0.48294801375339425]


In [2]:
l = []
for i in range(100):
    l.append(random.randint(1,10))
print(l)    

[9, 2, 10, 1, 10, 2, 2, 3, 4, 8, 8, 2, 7, 3, 5, 10, 7, 10, 4, 3, 5, 8, 7, 1, 2, 2, 4, 6, 7, 9, 8, 5, 5, 10, 2, 2, 7, 6, 6, 8, 1, 5, 9, 1, 6, 7, 9, 4, 5, 9, 10, 8, 7, 1, 1, 8, 7, 8, 3, 3, 2, 5, 4, 10, 8, 9, 7, 10, 10, 10, 4, 8, 1, 7, 8, 4, 2, 4, 5, 9, 8, 2, 6, 3, 6, 1, 2, 6, 2, 2, 3, 10, 3, 5, 10, 4, 10, 5, 2, 3]


In [9]:
l = []
for i in range(100):
    l.append(random.randint(1,365))
l.sort()    
print(l)    

i = 0
flag = 0 # Denotes that there is no repetition.
while( i < len(l)-1 ):
    if( l[i] == l[i+1] ):
        print('Repeats')
        flag = 1
        break
    i = i+1    
if(flag == 0):
    print("Doesn't repeat")

[5, 5, 8, 9, 20, 25, 28, 29, 35, 40, 51, 51, 52, 53, 55, 56, 60, 68, 68, 68, 73, 77, 77, 79, 80, 80, 83, 86, 97, 98, 98, 100, 101, 108, 114, 119, 124, 126, 130, 138, 148, 150, 150, 152, 156, 157, 157, 161, 161, 165, 166, 166, 171, 172, 176, 178, 186, 187, 189, 192, 193, 202, 203, 204, 206, 219, 220, 221, 227, 230, 231, 234, 235, 236, 239, 245, 248, 248, 251, 252, 252, 254, 254, 274, 279, 281, 285, 289, 296, 311, 312, 323, 325, 327, 329, 345, 346, 347, 348, 364]
Repeats


### Naive search in a list.

In [7]:
import random
l = []
n = int(input('Enter a number:'))
for i in range(1000000):
    l.append(random.randint(1,10000000))
flag = 0
for i in range(len(l)):
    if(n == l[i]):
        print("Hip Hip Hurray, element found.")
        flag = 1
        break
if(flag == 0):
    print('Element not found.')

Enter a number:5678
Hip Hip Hurray, element found.


### The obvious sort.

In [8]:
l = [12,10,7,18,6,42,8,35]
l.sort()
print(l)

[6, 7, 8, 10, 12, 18, 35, 42]


In [17]:
# What if we do not want to use any in-built function? Let's get our hands wet using the first principles.
l = [12,10,7,18,6,42,8,35,7,7]
x = []

while(len(l) > 0):
    min = l[0]
    for i in range(len(l)):
        if(min > l[i]):
           min = l[i]
    l.remove(min)
    x.append(min)
print(x)
print(l)

[6, 7, 7, 7, 8, 10, 12, 18, 35, 42]
[]


### Dot Product.

In [18]:
l = [1,3,4,67,18,17]
sum = 0
for i in range(len(l)):
    sum+=l[i]
print(sum)    

110


In [19]:
l = random.sample(list(range(10000)),1000)
sum = 0
for i in range(len(l)):
    sum+=l[i]
print(sum)

5121710


In [20]:
x = [1,7,3,4]
y = [8,6,3,2]
sum = 0
for i in range(len(x)):
    sum += x[i]*y[i]
print(sum)    

67


In [1]:
dim = 3
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

s1 = [1,2,1]
s2 = [6,2,3]
s3 = [4,2,1]

A = []
A.append(r1)
A.append(r2)
A.append(r3)

B = []
B.append(s1)
B.append(s2)
B.append(s3)

C = [[0,0,0], [0,0,0], [0,0,0]]       # It won't work if initialize C as C = [ [],[],[] ]
for i in range(dim):
    for j in range(dim):
        C[i][j] = A[i][j]+B[i][j]     
        
print(C)        
        

[[2, 4, 4], [10, 7, 9], [11, 10, 10]]


In [4]:
dim = 4
r1 = [1,2,3,4]
r2 = [5,6,7,8]
r3 = [9,10,11,12]
r4 = [13,14,15,16]

s1 = [1,2,1,2]
s2 = [6,2,3,2]
s3 = [4,2,1,3]
s4 = [7,8,9,10]

A = []
A.append(r1)
A.append(r2)
A.append(r3)
A.append(r4)

B = []
B.append(s1)
B.append(s2)
B.append(s3)
B.append(s4)

C = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for i in range(dim):
    for j in range(dim):
        C[i][j] = A[i][j]+B[i][j]
print(C)        

[[2, 4, 4, 6], [11, 8, 10, 10], [13, 12, 12, 15], [20, 22, 24, 26]]


### Matrix Multiplication - 1 & 2.

In [5]:
dim = 3
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

s1 = [1,2,1]
s2 = [6,2,3]
s3 = [4,2,1]

A = []
B = []
A.append(r1)
A.append(r2)
A.append(r3)

B.append(s1)
B.append(s2)
B.append(s3)
C = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(dim):
    for j in range(dim):
        for k in range(dim):
            C[i][j] = C[i][j]+A[i][k]*B[k][j]
print(C)

[[25, 12, 10], [58, 30, 25], [91, 48, 40]]


In [6]:
#Alternatively...
import numpy as np
X = np.mat(A)
Y = np.mat(B)
print(X*Y)

[[25 12 10]
 [58 30 25]
 [91 48 40]]
